apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenantb-kafka-client-role-binding
  namespace: testing
subjects:
- kind: ServiceAccount
  name: default
  namespace: tenantb
roleRef:
  kind: Role
  name: tenantb-kafka-client-user-role
  apiGroup: rbac.authorization.k8s.io
