apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../kafka-setup/base/
namespace: testing
namePrefix: testing-

replacements:
- source:
    kind: ConfigMap
    name: testing-kafka-metrics
    version: v1
  targets:
  - select: 
      kind: Kafka
      name: testing-strimzi-cluster
    fieldPaths:
    - spec.kafka.metricsConfig.valueFrom.configMapKeyRef.name
    
  - select: 
      kind: Kafka
      name: testing-strimzi-cluster
    fieldPaths:
    - spec.zookeeper.metricsConfig.valueFrom.configMapKeyRef.name
